import { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import { ExitModal } from "@/components/modals/exit-modal";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  "use cache";
  return (
    <html className={cn("font-sans", inter.variable)}>
      <body className="min-h-full flex flex-col">
        {/* //TODO: add Suspense fallback */}
        <ClerkProvider afterSignOutUrl="/">
          <Toaster />
          <ExitModal />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
