import { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PracticeModal } from "@/components/modals/practice-modal";
import { Suspense } from "react";
import Skeleton from "@/components/ui/skeleton";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  "use cache";
  //not protected, public route
  return (
    <html className={cn("font-sans", inter.variable)}>
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<Skeleton />}>

        <ClerkProvider afterSignOutUrl="/">
          <Toaster />
          <ExitModal />
          <HeartsModal />
          <PracticeModal />
          {children}
        </ClerkProvider>
        </Suspense>
      </body>
    </html>
  );
}
